name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t piotrfranekjan/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true piotrfranekjan/docker-react npm run test
